name: Render
on: [pull_request]:
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:

          service-id: ${{secrets.SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
       

          retries: 20
          wait: 16000
          sleep: 30000